crawler:
  path-to-cache: /var/tx_cache
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/indexed_likelib
    username: postgres
    password: postgres

  flyway:
    encoding: UTF-8
    baseline-on-migrate: true
#    schemas:
#      -likelib