crawler:
  path-to-cache: /opt/tx_cache
spring:
  datasource:
    url: jdbc:postgresql://changeme:xxxx/change_db
    username: changeme
    password: changeme

  flyway:
    encoding: UTF-8
    enabled: false