spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/q_main_db
    username: postgres
    password: postgres

  flyway:
    encoding: UTF-8
    baseline-on-migrate: true
    schemas:
      -likelib